---
- include_vars : cloud_creds.yml
- name: install python
  raw : sudo apt update & sudo apt install python3 python -y
- name : test playbook
  shell: echo '{{ aws_access_key_id }}' >> test_a.txt
- shell: echo '{{ aws_secret_key }}' >> test_a.txt